<a href="https://colab.research.google.com/github/abdullahmuaad9/AraVec-1/blob/main/misogyny_OR_not_OR_SEX_OR__8_Classification_19_ML_ALGORITHM_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import itertools
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
df=pd.read_csv('/content/ArMI2021_training.tsv',delimiter='\t',encoding='utf-8')


In [ ]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score,accuracy_score
from sklearn.metrics import confusion_matrix
from scipy import stats
import pylab as pl
from sklearn.preprocessing import LabelEncoder

In [ ]:
df.head

<bound method NDFrame.head of       tweet_id  ...   category
0            0  ...       none
1            1  ...  discredit
2            2  ...       none
3            3  ...       none
4            4  ...       none
...        ...  ...        ...
7861      7861  ...  discredit
7862      7862  ...       none
7863      7863  ...    damning
7864      7864  ...  discredit
7865      7865  ...  discredit

[7866 rows x 4 columns]>

In [ ]:
print(df.shape)
print(df.head())
labels = df.category
print(labels)
X_train, X_test, y_train, y_test = train_test_split(df['text'], labels, test_size = 0.2, random_state = 7) 

(7866, 4)
   tweet_id  ...   category
0         0  ...       none
1         1  ...  discredit
2         2  ...       none
3         3  ...       none
4         4  ...       none

[5 rows x 4 columns]
0            none
1       discredit
2            none
3            none
4            none
          ...    
7861    discredit
7862         none
7863      damning
7864    discredit
7865    discredit
Name: category, Length: 7866, dtype: object


In [ ]:
tfidf_vectorizer=TfidfVectorizer(stop_words='english', max_df=0.7)
tfidf_train=tfidf_vectorizer.fit_transform(X_train) 
tfidf_test=tfidf_vectorizer.transform(X_test)



In [ ]:
pac=PassiveAggressiveClassifier(max_iter=50)
pac.fit(tfidf_train,y_train)
y_pred=pac.predict(tfidf_test)
score=accuracy_score(y_test,y_pred)
print(f'Accuracy: {round(score*100,2)}%')

Accuracy: 71.66%


In [ ]:
#Confusion matrix to summarize the goodness of classification
confusion_matrix(y_test,y_pred, labels=['none','discredit','damning','threat of violence','dominance','stereotyping & objectification','threat of violence','sexual harassment'])


array([[478,  80,   8,   0,   7,  13,   3,   0],
       [112, 440,  11,   0,   5,  19,   6,   0],
       [ 16,  13, 104,   0,   0,   1,   4,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0],
       [  9,  16,   0,   0,  15,   4,   1,   0],
       [ 22,  32,   1,   0,   4,  81,   0,   1],
       [ 10,  14,   2,   0,   1,   3,   7,   0],
       [  2,   5,   0,   0,   1,   0,   2,   1]])

In [ ]:
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

                                precision    recall  f1-score   support

                       damning       0.82      0.75      0.78       138
                     derailing       0.33      0.12      0.18        16
                     discredit       0.73      0.74      0.73       594
                     dominance       0.44      0.33      0.38        45
                          none       0.73      0.81      0.77       591
             sexual harassment       0.50      0.09      0.15        11
stereotyping & objectification       0.67      0.57      0.62       141
            threat of violence       0.29      0.18      0.23        38

                      accuracy                           0.72      1574
                     macro avg       0.56      0.45      0.48      1574
                  weighted avg       0.71      0.72      0.71      1574

[[104   0  13   0  16   0   1   4]
 [  1   2   6   1   5   0   0   1]
 [ 11   1 440   5 112   0  19   6]
 [  0   0  16  15   9   0   

In [ ]:
from sklearn.linear_model import LinearRegression

le = LabelEncoder()
y_train= le.fit_transform(y_train)
y_test= le.fit_transform(y_test)

modelLR = LinearRegression()

modelLR.fit(tfidf_train,y_train)

y_pred=modelLR.predict(tfidf_test)

score=accuracy_score(y_test,y_pred)

print(f'Accuracy: {round(score*100,2)}%')
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))


ValueError: ignored

In [ ]:
from sklearn.linear_model import LogisticRegression
le = LabelEncoder()
y_train= le.fit_transform(y_train)
y_test= le.fit_transform(y_test)

modelLR = LogisticRegression()

modelLR.fit(tfidf_train,y_train)

y_pred=modelLR.predict(tfidf_test)

score=accuracy_score(y_test,y_pred)

print(f'Accuracy: {round(score*100,2)}%')
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))


Accuracy: 69.0%
              precision    recall  f1-score   support

           0       0.89      0.57      0.70       138
           1       0.00      0.00      0.00        16
           2       0.67      0.75      0.71       594
           3       1.00      0.11      0.20        45
           4       0.67      0.86      0.76       591
           5       0.00      0.00      0.00        11
           6       0.73      0.35      0.47       141
           7       0.50      0.03      0.05        38

    accuracy                           0.69      1574
   macro avg       0.56      0.33      0.36      1574
weighted avg       0.69      0.69      0.66      1574

[[ 79   0  30   0  29   0   0   0]
 [  0   0   8   0   8   0   0   0]
 [  3   0 444   0 137   0  10   0]
 [  0   0  27   5   8   0   4   1]
 [  4   0  76   0 508   0   3   0]
 [  0   0   7   0   4   0   0   0]
 [  1   0  54   0  37   0  49   0]
 [  2   0  12   0  22   0   1   1]]


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from sklearn.ensemble import RandomForestClassifier

le = LabelEncoder()
y_train= le.fit_transform(y_train)
y_test= le.fit_transform(y_test)

ModeRF=RandomForestClassifier(max_depth=2)

ModeRF.fit(tfidf_train,y_train)

y_pred=ModeRF.predict(tfidf_test)


score=accuracy_score(y_test,y_pred)

print(f'Accuracy: {round(score*100,2)}%')
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))


Accuracy: 38.82%
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       138
           1       0.00      0.00      0.00        16
           2       0.91      0.03      0.06       594
           3       0.00      0.00      0.00        45
           4       0.38      1.00      0.55       591
           5       0.00      0.00      0.00        11
           6       0.00      0.00      0.00       141
           7       0.00      0.00      0.00        38

    accuracy                           0.39      1574
   macro avg       0.16      0.13      0.08      1574
weighted avg       0.49      0.39      0.23      1574

[[  0   0   1   0 137   0   0   0]
 [  0   0   0   0  16   0   0   0]
 [  0   0  20   0 574   0   0   0]
 [  0   0   1   0  44   0   0   0]
 [  0   0   0   0 591   0   0   0]
 [  0   0   0   0  11   0   0   0]
 [  0   0   0   0 141   0   0   0]
 [  0   0   0   0  38   0   0   0]]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from sklearn.tree import DecisionTreeClassifier
le = LabelEncoder()
y_train= le.fit_transform(y_train)
y_test= le.fit_transform(y_test)
ModelDT = DecisionTreeClassifier()



ModelDT.fit(tfidf_train,y_train)

y_pred=ModelDT.predict(tfidf_test)


score=accuracy_score(y_test,y_pred)

print(f'Accuracy: {round(score*100,2)}%')
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))


Accuracy: 56.16%
              precision    recall  f1-score   support

           0       0.72      0.46      0.56       138
           1       0.05      0.06      0.06        16
           2       0.56      0.64      0.60       594
           3       0.32      0.27      0.29        45
           4       0.61      0.62      0.61       591
           5       0.00      0.00      0.00        11
           6       0.51      0.40      0.45       141
           7       0.19      0.13      0.15        38

    accuracy                           0.56      1574
   macro avg       0.37      0.32      0.34      1574
weighted avg       0.56      0.56      0.56      1574

[[ 63   4  29   3  35   1   3   0]
 [  1   1   7   0   5   0   1   1]
 [ 12   3 379  11 156   5  23   5]
 [  0   3  14  12   5   2   5   4]
 [  9   6 174   8 367   2  19   6]
 [  1   0   5   0   3   0   0   2]
 [  1   1  51   3  21   3  57   4]
 [  1   1  15   0  12   1   3   5]]


In [ ]:
from sklearn.neighbors import KNeighborsClassifier


le = LabelEncoder()
y_train= le.fit_transform(y_train)
y_test= le.fit_transform(y_test)


modelLR = KNeighborsClassifier(n_neighbors=1)

modelLR.fit(tfidf_train,y_train)

y_pred=modelLR.predict(tfidf_test)

score=accuracy_score(y_test,y_pred)

print(f'Accuracy: {round(score*100,2)}%')
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Accuracy: 43.27%
              precision    recall  f1-score   support

           0       0.82      0.17      0.28       138
           1       0.00      0.00      0.00        16
           2       0.40      0.97      0.57       594
           3       0.33      0.04      0.08        45
           4       0.83      0.11      0.19       591
           5       1.00      0.09      0.17        11
           6       0.75      0.09      0.15       141
           7       0.67      0.11      0.18        38

    accuracy                           0.43      1574
   macro avg       0.60      0.20      0.20      1574
weighted avg       0.63      0.43      0.33      1574

[[ 23   0 112   0   2   0   1   0]
 [  0   0  16   0   0   0   0   0]
 [  4   0 575   3   8   0   3   1]
 [  0   0  43   2   0   0   0   0]
 [  0   0 525   1  64   0   0   1]
 [  0   0   9   0   1   1   0   0]
 [  0   0 127   0   2   0  12   0]
 [  1   0  33   0   0   0   0   4]]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from sklearn.naive_bayes import GaussianNB
le = LabelEncoder()
y_train= le.fit_transform(y_train)
y_test= le.fit_transform(y_test)

modelLR = GaussianNB()


modelLR.fit(tfidf_train,y_train)

y_pred=modelLR.predict(tfidf_test)

score=accuracy_score(y_test,y_pred)

print(f'Accuracy: {round(score*100,2)}%')
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

TypeError: ignored

In [ ]:
from sklearn.svm import LinearSVC

le = LabelEncoder()
y_train= le.fit_transform(y_train)
y_test= le.fit_transform(y_test)

modelLR = LinearSVC()


modelLR.fit(tfidf_train,y_train)

y_pred=modelLR.predict(tfidf_test)

score=accuracy_score(y_test,y_pred)

print(f'Accuracy: {round(score*100,2)}%')
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Accuracy: 73.19%
              precision    recall  f1-score   support

           0       0.88      0.75      0.81       138
           1       0.00      0.00      0.00        16
           2       0.73      0.76      0.75       594
           3       0.57      0.29      0.38        45
           4       0.72      0.85      0.78       591
           5       1.00      0.09      0.17        11
           6       0.74      0.55      0.63       141
           7       0.29      0.13      0.18        38

    accuracy                           0.73      1574
   macro avg       0.62      0.43      0.46      1574
weighted avg       0.72      0.73      0.72      1574

[[103   0  14   0  18   0   1   2]
 [  0   0   6   1   8   0   0   1]
 [  5   0 451   2 116   0  15   5]
 [  0   0  19  13   8   0   4   1]
 [  5   0  73   5 501   0   5   2]
 [  0   0   6   0   3   1   0   1]
 [  1   0  32   2  28   0  78   0]
 [  3   0  13   0  14   0   3   5]]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from sklearn.svm import SVC

le = LabelEncoder()
y_train= le.fit_transform(y_train)
y_test= le.fit_transform(y_test)

modelLR = SVC()


modelLR.fit(tfidf_train,y_train)

y_pred=modelLR.predict(tfidf_test)

score=accuracy_score(y_test,y_pred)

print(f'Accuracy: {round(score*100,2)}%')
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Accuracy: 67.66%
              precision    recall  f1-score   support

           0       0.89      0.56      0.68       138
           1       0.00      0.00      0.00        16
           2       0.67      0.72      0.69       594
           3       0.75      0.07      0.12        45
           4       0.65      0.87      0.75       591
           5       0.00      0.00      0.00        11
           6       0.75      0.33      0.46       141
           7       0.50      0.03      0.05        38

    accuracy                           0.68      1574
   macro avg       0.53      0.32      0.34      1574
weighted avg       0.68      0.68      0.65      1574

[[ 77   0  32   0  28   0   1   0]
 [  0   0   8   0   8   0   0   0]
 [  6   0 426   0 156   0   6   0]
 [  0   0  28   3   9   0   4   1]
 [  3   0  72   1 512   0   3   0]
 [  0   0   7   0   4   0   0   0]
 [  0   0  54   0  41   0  46   0]
 [  1   0  11   0  24   0   1   1]]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from sklearn.neighbors import  RadiusNeighborsClassifier

le = LabelEncoder()
y_train= le.fit_transform(y_train)
y_test= le.fit_transform(y_test)

modelLR=RadiusNeighborsClassifier(radius=8.0)


modelLR.fit(tfidf_train,y_train)

y_pred=modelLR.predict(tfidf_test)

score=accuracy_score(y_test,y_pred)

print(f'Accuracy: {round(score*100,2)}%')
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Accuracy: 37.55%
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       138
           1       0.00      0.00      0.00        16
           2       0.00      0.00      0.00       594
           3       0.00      0.00      0.00        45
           4       0.38      1.00      0.55       591
           5       0.00      0.00      0.00        11
           6       0.00      0.00      0.00       141
           7       0.00      0.00      0.00        38

    accuracy                           0.38      1574
   macro avg       0.05      0.12      0.07      1574
weighted avg       0.14      0.38      0.20      1574

[[  0   0   0   0 138   0   0   0]
 [  0   0   0   0  16   0   0   0]
 [  0   0   0   0 594   0   0   0]
 [  0   0   0   0  45   0   0   0]
 [  0   0   0   0 591   0   0   0]
 [  0   0   0   0  11   0   0   0]
 [  0   0   0   0 141   0   0   0]
 [  0   0   0   0  38   0   0   0]]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from sklearn.naive_bayes import BernoulliNB




le = LabelEncoder()
y_train= le.fit_transform(y_train)
y_test= le.fit_transform(y_test)


modelLR = BernoulliNB()

modelLR.fit(tfidf_train,y_train)

y_pred=modelLR.predict(tfidf_test)

score=accuracy_score(y_test,y_pred)

print(f'Accuracy: {round(score*100,2)}%')
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Accuracy: 62.77%
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       138
           1       0.00      0.00      0.00        16
           2       0.56      0.84      0.67       594
           3       0.00      0.00      0.00        45
           4       0.71      0.83      0.77       591
           5       0.00      0.00      0.00        11
           6       0.00      0.00      0.00       141
           7       0.00      0.00      0.00        38

    accuracy                           0.63      1574
   macro avg       0.16      0.21      0.18      1574
weighted avg       0.48      0.63      0.54      1574

[[  0   0 105   0  33   0   0   0]
 [  0   0  11   0   5   0   0   0]
 [  0   0 498   0  96   0   0   0]
 [  0   0  38   0   7   0   0   0]
 [  0   0 101   0 490   0   0   0]
 [  0   0   7   0   4   0   0   0]
 [  0   0 106   0  35   0   0   0]
 [  0   0  20   0  18   0   0   0]]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from sklearn.tree import ExtraTreeClassifier



le = LabelEncoder()
y_train= le.fit_transform(y_train)
y_test= le.fit_transform(y_test)


modelLR = ExtraTreeClassifier()

modelLR.fit(tfidf_train,y_train)

y_pred=modelLR.predict(tfidf_test)

score=accuracy_score(y_test,y_pred)

print(f'Accuracy: {round(score*100,2)}%')
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Accuracy: 52.6%
              precision    recall  f1-score   support

           0       0.55      0.41      0.47       138
           1       0.00      0.00      0.00        16
           2       0.52      0.55      0.53       594
           3       0.38      0.29      0.33        45
           4       0.58      0.64      0.61       591
           5       0.40      0.18      0.25        11
           6       0.43      0.35      0.38       141
           7       0.12      0.08      0.10        38

    accuracy                           0.53      1574
   macro avg       0.37      0.31      0.33      1574
weighted avg       0.52      0.53      0.52      1574

[[ 57   2  36   2  31   0   6   4]
 [  1   0   9   1   4   0   0   1]
 [ 28   8 327   9 179   1  34   8]
 [  0   1  16  13   6   0   6   3]
 [  9   5 176   4 377   0  18   2]
 [  1   0   5   0   3   2   0   0]
 [  4   1  46   3  33   2  49   3]
 [  4   0  15   2  13   0   1   3]]


In [ ]:
from sklearn.ensemble import BaggingClassifier





le = LabelEncoder()
y_train= le.fit_transform(y_train)
y_test= le.fit_transform(y_test)


modelLR =BaggingClassifier()

modelLR.fit(tfidf_train,y_train)

y_pred=modelLR.predict(tfidf_test)

score=accuracy_score(y_test,y_pred)

print(f'Accuracy: {round(score*100,2)}%')
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Accuracy: 60.74%
              precision    recall  f1-score   support

           0       0.80      0.54      0.64       138
           1       0.00      0.00      0.00        16
           2       0.58      0.70      0.64       594
           3       0.56      0.31      0.40        45
           4       0.61      0.67      0.64       591
           5       0.00      0.00      0.00        11
           6       0.70      0.38      0.49       141
           7       0.27      0.11      0.15        38

    accuracy                           0.61      1574
   macro avg       0.44      0.34      0.37      1574
weighted avg       0.60      0.61      0.59      1574

[[ 74   0  28   2  33   0   1   0]
 [  1   0   9   0   5   0   0   1]
 [  9   0 416   3 156   0  10   0]
 [  0   0  14  14   8   0   5   4]
 [  5   0 180   3 395   0   6   2]
 [  0   0   4   0   5   0   0   2]
 [  1   0  50   3  32   0  53   2]
 [  3   0  14   0  16   0   1   4]]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from sklearn.ensemble import AdaBoostClassifier





le = LabelEncoder()
y_train= le.fit_transform(y_train)
y_test= le.fit_transform(y_test)


modelLR = AdaBoostClassifier()

modelLR.fit(tfidf_train,y_train)

y_pred=modelLR.predict(tfidf_test)

score=accuracy_score(y_test,y_pred)

print(f'Accuracy: {round(score*100,2)}%')
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Accuracy: 44.35%
              precision    recall  f1-score   support

           0       0.74      0.27      0.39       138
           1       0.38      0.19      0.25        16
           2       0.40      0.08      0.14       594
           3       0.29      0.09      0.14        45
           4       0.42      0.93      0.58       591
           5       0.00      0.00      0.00        11
           6       0.78      0.38      0.51       141
           7       0.29      0.05      0.09        38

    accuracy                           0.44      1574
   macro avg       0.41      0.25      0.26      1574
weighted avg       0.46      0.44      0.36      1574

[[ 37   0  12   0  89   0   0   0]
 [  0   3   3   0   9   0   0   1]
 [  7   2  50   3 524   0   7   1]
 [  0   0  21   4  14   0   4   2]
 [  4   3  27   5 548   0   3   1]
 [  0   0   0   0  11   0   0   0]
 [  0   0   9   2  76   0  54   0]
 [  2   0   4   0  29   0   1   2]]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from sklearn.ensemble import GradientBoostingClassifier






le = LabelEncoder()
y_train= le.fit_transform(y_train)
y_test= le.fit_transform(y_test)


modelLR =GradientBoostingClassifier()

modelLR.fit(tfidf_train,y_train)

y_pred=modelLR.predict(tfidf_test)

score=accuracy_score(y_test,y_pred)

print(f'Accuracy: {round(score*100,2)}%')
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Accuracy: 63.41%
              precision    recall  f1-score   support

           0       0.84      0.54      0.66       138
           1       0.11      0.12      0.12        16
           2       0.68      0.58      0.63       594
           3       0.32      0.18      0.23        45
           4       0.61      0.83      0.70       591
           5       0.25      0.09      0.13        11
           6       0.74      0.48      0.58       141
           7       0.25      0.21      0.23        38

    accuracy                           0.63      1574
   macro avg       0.48      0.38      0.41      1574
weighted avg       0.64      0.63      0.62      1574

[[ 75   3  14   1  38   1   2   4]
 [  0   2   5   0   7   0   0   2]
 [  8   6 345   7 210   0  12   6]
 [  0   0  18   8  13   0   4   2]
 [  4   4  76   5 492   1   4   5]
 [  0   0   4   0   5   1   0   1]
 [  0   1  36   2  30   1  67   4]
 [  2   2   8   2  14   0   2   8]]


In [ ]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis




le = LabelEncoder()
y_train= le.fit_transform(y_train)
y_test= le.fit_transform(y_test)


modelLR=LinearDiscriminantAnalysis()

modelLR.fit(tfidf_train,y_train)

y_pred=modelLR.predict(tfidf_test)

score=accuracy_score(y_test,y_pred)

print(f'Accuracy: {round(score*100,2)}%')
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

TypeError: ignored

In [ ]:
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis





le = LabelEncoder()
y_train= le.fit_transform(y_train)
y_test= le.fit_transform(y_test)


modelLR =QuadraticDiscriminantAnalysis()

modelLR.fit(tfidf_train,y_train)

y_pred=modelLR.predict(tfidf_test)

score=accuracy_score(y_test,y_pred)

print(f'Accuracy: {round(score*100,2)}%')
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))